---
# =============================================================================
#  Nav2 parameters for a 2‑wheel differential robot
#  max_lin_vel = 0.18 m/s,  max_ang_vel = 0.8 rad/s
# =============================================================================

###############################################################################
# Map & Localization
###############################################################################
map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/home/cy/Study/Nav_ws/maps/B406_half_map.yaml"

amcl:
  ros__parameters:
    base_frame_id: base_link
    use_sim_time: false
    scan_topic: scan
    min_particles: 500
    max_particles: 2000
    alpha1: 0.2 # Laser / odom noise parameters，可按需微调
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    update_min_d: 0.1 # 每 0.1 m 更新一次
    update_min_a: 0.1 # 每 0.1 rad 更新一次
    resample_interval: 1
    tf_broadcast: true

###############################################################################
# Global Planner
###############################################################################
planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: true

###############################################################################
# Path Smoother
###############################################################################
smoother_server:
  ros__parameters:
    use_sim_time: false
    smoother_plugins: ["SimpleSmoother"]

    SimpleSmoother:
      plugin: "nav2_constrained_smoother/ConstrainedSmoother"

###############################################################################
# Local Planner / Controller
###############################################################################
controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      allow_reversing: false

      # ------------ 运动约束 ------------
      min_vel_x: 0.0
      max_vel_x: 0.18
      min_vel_theta: -0.8
      max_vel_theta: 0.8
      acc_lim_x: 1.0
      decel_lim_x: -1.0
      acc_lim_theta: 2.0
      decel_lim_theta: -2.0

      # ------------ 采样 & 预测 ------------
      vx_samples: 20
      vtheta_samples: 40
      sim_time: 1.5

      # ------------ 评价器（Critics）------------
      critics:
        - ObstacleFootprintCritic
        - GoalAlignCritic
        - PathAlignCritic
        - RotateToGoalCritic
        - PreferForwardCritic

      ObstacleFootprintCritic:
        plugin: "dwb_critics::ObstacleFootprintCritic"
      GoalAlignCritic:
        plugin: "dwb_critics::GoalAlignCritic"
      PathAlignCritic:
        plugin: "dwb_critics::PathAlignCritic"
      RotateToGoalCritic:
        plugin: "dwb_critics::RotateToGoalCritic"
      PreferForwardCritic:
        plugin: "dwb_critics::PreferForwardCritic"

###############################################################################
# Recovery / Behavior Plugins
###############################################################################
behavior_server:
  ros__parameters:
    use_sim_time: false
    behavior_plugins: ["spin", "backup", "drive_on_heading"]

    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"

###############################################################################
# Behavior‑Tree Navigator
###############################################################################
bt_navigator:
  ros__parameters:
    use_sim_time: false

    # —— 1. 单点导航行为树（NavigateToPose） ——
    # 官方推荐文件：带 replanning + recovery 的版本
    default_nav_to_pose_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"

    # —— 2. 多点路径导航行为树（NavigateThroughPoses） ——
    # 用于执行多个目标点导航任务
    default_nav_through_poses_bt_xml: "/home/cy/Study/Nav_ws/config/nav_through_poses_without_wait.xml"
###############################################################################
# Global Costmap
###############################################################################
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_link
      update_frequency: 1.0
      publish_frequency: 1.0
      width: 400
      height: 400
      resolution: 0.05
      robot_radius: 0.15

      plugins:
        - static_layer
        - obstacle_layer
        - inflation_layer

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: LaserScan

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.3

###############################################################################
# Local Costmap
###############################################################################
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_link

      rolling_window: true # ✨ 关键！让窗口跟随机器人
      width: 3 # 单位：米
      height: 3 # 单位：米
      resolution: 0.05
      robot_radius: 0.15

      update_frequency: 5.0
      publish_frequency: 2.0

      plugins: # 如需 static_layer 可自行添加
        - obstacle_layer
        - inflation_layer

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: scan
          data_type: LaserScan
          max_obstacle_height: 2.0
          clearing: true
          marking: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.3
