controller_server:
  ros__parameters:
    use_sim_time: false

    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.0
    min_theta_velocity_threshold: 0.001

    controller_plugins: ["FollowPath"]
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.05
      movement_time_allowance: 5.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.1
      stateful: true

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false

      min_vel_x: 0.0
      max_vel_x: 0.15 # 你小车的最大线速度
      min_speed_xy: 0.0
      max_speed_xy: 0.15
      max_vel_theta: 0.6 # 最大角速度
      min_speed_theta: 0.0

      acc_lim_x: 0.3
      acc_lim_theta: 1.0
      decel_lim_x: -0.3
      decel_lim_theta: -1.0

      vx_samples: 10
      vtheta_samples: 20
      sim_time: 1.5

      linear_granularity: 0.05
      angular_granularity: 0.025
      time_granularity: 0.025

      critics:
        [
          "dwb_critics::ObstacleFootprintCritic",
          "dwb_critics::GoalAlignCritic",
          "dwb_critics::PathAlignCritic",
          "dwb_critics::RotateToGoalCritic",
          "dwb_critics::PreferForwardCritic",
        ]

      dwb_critics::ObstacleFootprintCritic:
        scale: 0.01

      dwb_critics::GoalAlignCritic:
        scale: 24.0

      dwb_critics::PathAlignCritic:
        scale: 32.0

      dwb_critics::RotateToGoalCritic:
        scale: 32.0
        thresholds:
          min_angle: 0.785 # 约 45 度

      dwb_critics::PreferForwardCritic:
        scale: 10.0
