ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    two_d_mode: true

    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    publish_tf: true

    odometry0: /odom
    odometry0_config:
      [
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ]
    odometry0_differential: false
